name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - '**/*.json'
      - 'tokens.config.js'
      - 'package.json'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          scope: '@piacentinithiago'

      - name: Configure .npmrc for GitHub Packages
        run: |
          echo "@piacentinithiago:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build tokens
        run: npm run build:tokens

      - name: Publish package to GitHub Packages
        run: npm publish
